baseURL = "https://mabinouze.fr/"
locale = "fr-fr"
title = "Ma binouze"
enableInlineShortcodes = true
disableKinds = ['taxonomy', 'term', 'RSS']
theme = "mabinouze-v2"

[params]
icon = "🍺"
repository = "https://github.com/reveliant/mabinouze"
api = "https://api.mabinouze.fr/v1"

[markup.goldmark.renderer]
unsafe = true

[markup.goldmark.parser.attribute]
block = true
title = true

[security]
allowContent = ['text/html', 'text/markdown']