[[headers]]
  for = '/**'
  [headers.values]
    Content-Security-Policy = "default-src 'self'; base-uri 'none'; font-src 'self' https://cdnjs.cloudflare.com https://fonts.gstatic.com ; form-action 'none'; frame-ancestors 'self'; img-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://cdnjs.cloudflare.com; style-src 'self' 'unsafe-inline' https://cdnjs.cloudflare.com https://fonts.googleapis.com; connect-src 'self' localhost:5000"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "accelerometer=(), camera=(), geolocation=(), microphone=()"

[[headers]]
  for = "/*.svg"
  [headers.values]
    Content-Security-Policy = "default-src 'none'; style-src 'self' 'unsafe-inline'"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "accelerometer=(), camera=(), geolocation=(), microphone=()"

[[redirects]]
  from = "/*/"
  to = "/round/"
  status = 200

[[redirects]]
  from = "/*/details"
  to = "/details/"
  status = 200

[[redirects]]
  from = "/*"
  to = "404.html"
  status = 404